# Generated by Django 5.2.11 on 2026-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Couleur principale (hex).",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#111827",
                        help_text="Couleur secondaire (hex).",
                        max_length=7,
                    ),
                ),
                ("background_color", models.CharField(default="#F9FAFB", max_length=7)),
                ("text_color", models.CharField(default="#111827", max_length=7)),
                (
                    "font_family",
                    models.CharField(
                        default="Inter, system-ui, -apple-system, BlinkMacSystemFont",
                        max_length=100,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="themes/previews/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
            },
        ),
    ]
