# Generated by Django 5.2.11 on 2026-02-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("about", "À propos"),
                            ("projects", "Projets"),
                            ("skills", "Compétences"),
                            ("experience", "Expériences"),
                            ("education", "Éducation"),
                            ("contact", "Contact"),
                            ("custom", "Personnalisée"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant unique dans le portfolio (ancre de section).",
                        max_length=80,
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("portfolio", "slug")},
            },
        ),
    ]
